{% set name = "ffmpeg-normalize" %}
{% set version = "1.27.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slhck/ffmpeg-normalize/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b1f23fd1fa3697d3917f0a80dc6a2399b195a250eb395f3797aa5bbf7fae8690

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - ffmpeg-normalize = ffmpeg_normalize.__main__:main

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - tqdm >=4.64.1
    - colorama >=0.4.3
    - ffmpeg-progress-yield >=0.5.0
    - colorlog >=6.7.0

test:
  imports:
    - ffmpeg_normalize
  requires:
    - pip
  commands:
    - pip check
    - ffmpeg-normalize -h

about:
  home: https://github.com/slhck/ffmpeg-normalize
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Audio Normalization for Python/ffmpeg
  description: |
    A utility for batch-normalizing audio using ffmpeg.
    This program normalizes media files to a certain loudness level using the
    EBU R128 loudness normalization procedure. It can also perform RMS-based
    normalization (where the mean is lifted or attenuated), or peak
    normalization to a certain target level.
    An external installation of ffmpeg is reuqired.
  doc_url: https://github.com/slhck/ffmpeg-normalize/blob/master/README.md
  dev_url: https://github.com/slhck/ffmpeg-normalize/

extra:
  recipe-maintainers:
    - slhck
