{% set name = "ffmpeg-normalize" %}
{% set version = "1.24.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slhck/ffmpeg-normalize/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 11a7de0413ed41bf31d33546aa7d1b40ce4daf64e0eaa622116509c44518d906

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - ffmpeg-normalize = ffmpeg_normalize.__main__:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - tqdm >=4.38.0
    - colorama >=0.4.3
    - ffmpeg-progress-yield >=0.1.2

test:
  imports:
    - ffmpeg_normalize
  requires:
    - pip
  commands:
    - pip check
    - ffmpeg-normalize -h

about:
  home: https://github.com/slhck/ffmpeg-normalize
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Audio Normalization for Python/ffmpeg
  description: |
    A utility for batch-normalizing audio using ffmpeg.
    This program normalizes media files to a certain loudness level using the
    EBU R128 loudness normalization procedure. It can also perform RMS-based
    normalization (where the mean is lifted or attenuated), or peak
    normalization to a certain target level.
    An external installation of ffmpeg is reuqired.
  doc_url: https://github.com/slhck/ffmpeg-normalize/blob/master/README.md
  dev_url: https://github.com/slhck/ffmpeg-normalize/

extra:
  recipe-maintainers:
    - slhck
