{% set name = "ffmpeg-normalize" %}
{% set version = "1.33.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slhck/ffmpeg-normalize/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ab93964d5b056a5c1ac56c0b8957321ff2a255c7fbc60046d062ddd6c8d39b74

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - ffmpeg-normalize = ffmpeg_normalize.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - uv-build >=0.8.14
  run:
    - python >={{ python_min }}
    - tqdm >=4.64.1
    - colorama >=0.4.6
    - ffmpeg-progress-yield >=1.0.1
    - colorlog 6.7.0
    - mutagen >=1.47.0

test:
  imports:
    - ffmpeg_normalize
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - ffmpeg-normalize -h

about:
  home: https://github.com/slhck/ffmpeg-normalize
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Audio Normalization for Python/ffmpeg
  description: |
    A utility for batch-normalizing audio using ffmpeg.
    This program normalizes media files to a certain loudness level using the
    EBU R128 loudness normalization procedure. It can also perform RMS-based
    normalization (where the mean is lifted or attenuated), or peak
    normalization to a certain target level.
    An external installation of ffmpeg is reuqired.
  doc_url: https://github.com/slhck/ffmpeg-normalize/blob/master/README.md
  dev_url: https://github.com/slhck/ffmpeg-normalize/

extra:
  recipe-maintainers:
    - slhck
